name: 'Run sync'
on: [pull_request]
jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
        with:
          repository: srz-zumix/Zenn
          token: ${{ secrets.GITHUBPAT }}

